name: PyRXMesh
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - cmake>=3.24,<4
  - ninja
  - git
  - numpy>=1.26
  - pytest
  - scipy
  - pip:
      - --index-url https://download.pytorch.org/whl/cu126
      - torch
      - --extra-index-url https://pypi.org/simple
      - scikit-build-core>=0.12
      - pybind11>=2.13
