"""Create an external PyRXMesh differentiable-energy plugin."""

from __future__ import annotations

from pathlib import Path

from ._plugin_scaffold import cmake, create_plugin, pyproject, scaffold_main


def _source(module: str) -> str:
    return f"""#include <pybind11/pybind11.h>

#include <utility>

#include "pyrxmesh/diff_plugin_api.h"

namespace py = pybind11;
using namespace rxmesh;

using Problem =
    pyrxmesh::diff::ScalarGradientProblem<float, 3, VertexHandle>;

void add_terms(Problem& problem, py::dict params)
{{
    const float weight =
        params.contains("weight") ? params["weight"].cast<float>() : 1.0f;

    // Replace or extend this edge-quadratic example.
    problem.add_term<Op::EV>(
        [weight] __device__(const auto& eh,
                            const auto& iter,
                            auto&       x) {{
            using ActiveT = ACTIVE_TYPE(eh);
            const Eigen::Vector3<ActiveT> x0 =
                x.template active<3>(eh, iter, 0);
            const Eigen::Vector3<ActiveT> x1 =
                x.template active<3>(eh, iter, 1);
            return weight * (x0 - x1).squaredNorm();
        }});
}}

PYBIND11_MODULE(_{module}, m)
{{
    pyrxmesh::require_compatible_runtime(m);
    m.def(
        "make_energy",
        [](py::object mesh, py::dict params) {{
            return pyrxmesh::diff::make_scalar_energy<
                float, 3, VertexHandle>(
                    mesh, std::move(params), add_terms);
        }},
        py::arg("mesh"),
        py::arg("params") = py::dict());
}}
"""


def _init(module: str) -> str:
    return f"""from ._{module} import make_energy

__all__ = ["make_energy"]
"""


def _run_script(module: str) -> str:
    return f"""import argparse

import torch

import pyrxmesh as rx
import {module}


parser = argparse.ArgumentParser()
parser.add_argument("mesh")
parser.add_argument("--weight", type=float, default=1.0)
args = parser.parse_args()

rx.init(0)
mesh = rx.RXMeshStatic(args.mesh)
energy = {module}.make_energy(mesh, {{"weight": args.weight}})
x = torch.as_tensor(
    mesh.vertices(), dtype=torch.float32, device="cuda"
).requires_grad_()
loss = energy.torch(x)
loss.backward()
print("loss:", loss.item())
print("gradient shape:", tuple(x.grad.shape))
"""


def _readme(module: str) -> str:
    return f"""# {module}

Differentiable RXMesh energy generated by
`python -m pyrxmesh.diff_plugin init`.

Edit `src/{module}.cu`, rebuild, and run:

```bash
python -m pip install -v --no-build-isolation .
python run_energy.py path/to/mesh.obj
```

Add or replace `problem.add_term` calls in the CUDA source. Keep the scalar
type, variable dimension, and element handle consistent between `Problem` and
`make_scalar_energy`.

See PyRXMesh's `DIFFERENTIABLE_ENERGY_PLUGINS.md` for the term API, query
examples, fixed attributes, row order, and gradient validation.
"""


def init_plugin(module: str, output_dir: Path, force: bool = False) -> Path:
    """Create a buildable differentiable-energy plugin package."""

    return create_plugin(
        module,
        output_dir,
        {
            "pyproject.toml": pyproject(module, "Differentiable RXMesh energy"),
            "CMakeLists.txt": cmake(module),
            "README.md": _readme(module),
            "run_energy.py": _run_script(module),
            f"src/{module}.cu": _source(module),
            f"src/{module}/__init__.py": _init(module),
        },
        force=force,
    )


def main(argv: list[str] | None = None) -> None:
    scaffold_main(
        argv,
        description=__doc__ or "",
        help_text="Create a differentiable-energy plugin",
        example="my_energy",
        initializer=init_plugin,
    )


if __name__ == "__main__":
    main()
